repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
        - id: check-added-large-files
          name: Check for added large files
          entry: check-added-large-files
        - id: check-json
          name: Check JSON
        - id: detect-private-key
          name: Check for Sensitive Private keys
        - id: requirements-txt-fixer
          name: Reorder Requirements txt
        - id: check-toml
          name: Check Toml
          entry: check-toml
          types: [toml]
        - id: check-yaml
          name: Check Yaml
          entry: check-yaml
          types: [yaml]
        - id: end-of-file-fixer
          name: Fix End of Files
          entry: end-of-file-fixer
          types: [text]
          stages: [commit, push, manual]
        - id: trailing-whitespace
          name: Trim Trailing Whitespace
          entry: trailing-whitespace-fixer
          types: [text]
          stages: [commit, push, manual]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
        args: ["streamlit_app"]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
        args: ["--config=streamlit_app/.flake8", "streamlit_app"]
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: system
        types_or: [cython, pyi, python]
        args: ["--filter-files", "--profile=black", "streamlit_app"]
